trigger:
- main 

pool: default

variables:
  phpVersion: '8.3.2'

steps:
- script: |
    update-alternatives --set php /usr/bin/php$(phpVersion)
    update-alternatives --set phar /usr/bin/phar$(phpVersion)
    update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

- script: composer install --no-interaction --prefer-dist
  displayName: 'composer install'
- script: composer update
  displayName: 'composer update'
- script: php artisan test
  displayName: 'test artisan'

- script: phpunit --coverage-clover coverage.xml
- task: PublishCodeCoverageResults@2
  inputs:
    summaryFileLocation: 'coverage.xml'
    failIfCoverageEmpty: true
  displayName: 'Generate code coverage report'