# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: 8.^

steps:
- script: |
    sudo add-apt-repository ppa:ondrej/php -y
    sudo apt-get update
    sudo apt-get install php$(phpVersion) php$(phpVersion)-mbstring php$(phpVersion)-xml php$(phpVersion)-mysql php$(phpVersion)-curl php$(phpVersion)-json php$(phpVersion)-cli php$(phpVersion)-zip -y
    php -version
  displayName: 'Install PHP version $(phpVersion)'

- script: |
    curl -sS https://getcomposer.org/installer | php
    sudo mv composer.phar /usr/local/bin/composer
  displayName: 'Install Composer'

- script: composer install --no-interaction --prefer-dist
  displayName: 'composer install'

- script: cp .env.example .env
  displayName: 'Setup Environment File'

- script: php artisan key:generate
  displayName: 'Generate Application Key'

- script: php artisan migrate --force
  displayName: 'Run Database Migrations'